### ISSUE TITLE
Copy from Usenet

### ISSUE THREAD

**Issue by larsbrinkhoff** [larsbrinkhoff/sunview-x-mazewar#1]
Hello @kantarjiev,

I found this in comp.sources.sun.  Ok to put a copy here?

I'd send a post card, but I'm not sure the address is up to date.

**Comment by kantarjiev** [comment]
Sure!

I'm on Portola, don't remember what address is in there :-)

**Comment by larsbrinkhoff** [comment]
Thanks!

**Comment by kantarjiev** [comment]
Oh! No, the DECWRL address most certainly won't work. I left WRL in 1988, and DEC in 1990. DEC left that building in about 1992. DECWRL became part of Compaq, and then HP, and then, well ... pretty much everyone had left before it was officially disbanded.

I'm impressed that anyone still cares about this code. It was fun to work on and fun to play!
